## 1.	Write a Python Program to Add Two Matrices?

In [22]:
#generate the 2 matrix with random numbers
import numpy as np
mat1 = np.random.randint(1,10,(3,3))
mat2 = np.random.randint(1,10,(3,3))
#printing the array
print('Matrix 1')
print(mat1)
print("and")
print('Matrix 2')
print(mat2)
#adding the array
summ = mat1+mat2
print('The sum of the two matrixes is',summ)

Matrix 1
[[3 3 4]
 [8 6 6]
 [1 9 8]]
and
Matrix 2
[[2 8 9]
 [6 5 2]
 [2 3 5]]
The sum of the two matrixes is [[ 5 11 13]
 [14 11  8]
 [ 3 12 13]]


## 2.	Write a Python Program to Multiply Two Matrices?

In [23]:
#generate the 2 matrix with random numbers
import numpy as np
mat1 = np.random.randint(1,10,(3,3))
mat2 = np.random.randint(1,10,(3,3))
#printing the array
print('Matrix 1')
print(mat1)
print("and")
print('Matrix 2')
print(mat2)
#adding the array
summ = mat1*mat2
print('The multiplication of the two matrixes is',summ)

Matrix 1
[[5 1 4]
 [7 3 7]
 [8 2 2]]
and
Matrix 2
[[9 4 6]
 [4 7 3]
 [1 1 7]]
The multiplication of the two matrixes is [[45  4 24]
 [28 21 21]
 [ 8  2 14]]


## 3.	Write a Python Program to Transpose a Matrix?

In [31]:
matrix=mat1
print('The matrix is ')
print(matrix)
def transpose(a):
    return a.T
print('The transpose of the given matrix is',transpose(matrix))

The matrix is 
[[5 1 4]
 [7 3 7]
 [8 2 2]]
The transpose of the given matrix is [[5 7 8]
 [1 3 2]
 [4 7 2]]


## 4.	Write a Python Program to Sort Words in Alphabetic Order?

In [9]:
my_str = input("Enter a string: ")  
words = my_str.split() 
def sorted(s):
    words.sort()  
    for word in words:
        print(word)
sorted(words)

Enter a string: i am suabsh
am
i
suabsh


## 5.	Write a Python Program to Remove Punctuation From a String?

In [12]:
punctuation = '''''!()-[]{};:'"\,<>./?@#$%^&*_~'''  
my_str = input("Enter a string: ")  
no_punct = ""  
for char in my_str:  
    if char not in punctuation:  
        no_punct = no_punct + char  
print(no_punct)  


Enter a string: hi, i am subash.and this is my  8th assignment
hi i am subashand this is my  8th assignment
