# Numpy

In [3]:
import numpy as np

In [4]:
l=[1,2,3,4,5]

In [5]:
np.array(l)

array([1, 2, 3, 4, 5])

In [6]:
l1 = [4,5,6,7,"Subash",23.1]

In [12]:
a1 = np.array(l1)

In [13]:
a2 = np.array([[1,2,3],[4,5,6]])

# 3D array

In [14]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [15]:
a1

array(['4', '5', '6', '7', 'Subash', '23.1'], dtype='<U32')

In [16]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [18]:
#to know the array dimenstion
a1.ndim

1

In [19]:
a2.ndim

2

In [20]:
a3.ndim

3

In [23]:
#size will give the total number of the elements inside the array
a1.size

6

In [24]:
a2.size

6

In [25]:
a3.size

9

In [26]:
a1.shape #it will show the shape of the array(6*)

(6,)

In [29]:
a2.shape #it will show the shape of the array(2*3)

(2, 3)

In [30]:
a3.shape #it will show the shape of the array(1,3*3)(z,y,x)

(1, 3, 3)

# Random function

In [32]:
np.random.randint(2,50)

39

In [39]:
np.random.randint(1,100,(3,4)) #(3,4 is shape of the array which we are expecting)

array([[31, 62, 61, 33],
       [83, 69, 81, 16],
       [28, 32, 60, 74]])

In [40]:
np.random.randint(1,50,(2,3,4)) #(3*4 array with 2 matrix)

array([[[24, 36, 10, 14],
        [21, 45,  7, 19],
        [26, 35, 22,  5]],

       [[45, 32, 25, 24],
        [ 2, 30, 43, 15],
        [14, 48,  9, 44]]])

# rand

In [43]:
np.random.rand(2,3)

array([[0.67616566, 0.37932681, 0.6897485 ],
       [0.08200664, 0.52718689, 0.93612597]])

# randn

In [52]:
a4 = np.random.randn(4,4)

In [53]:
a4.reshape(8,2) #while reshaping the array the size should be same(ex4*4 = 16 reshape(2,8)or(8,2)or(1,16))

array([[-1.14243864e+00,  1.29765299e+00],
       [ 2.27934243e-01,  8.76929194e-01],
       [ 1.06671083e-01,  5.47387262e-01],
       [-3.82816813e-02,  1.86633641e-03],
       [ 6.42463694e-01,  4.89170873e-01],
       [-9.57545721e-01, -6.55136381e-01],
       [-1.94175489e+00,  2.13605243e+00],
       [-1.30989594e+00,  2.14321191e+00]])

In [54]:
a4.reshape(16,1)

array([[-1.14243864e+00],
       [ 1.29765299e+00],
       [ 2.27934243e-01],
       [ 8.76929194e-01],
       [ 1.06671083e-01],
       [ 5.47387262e-01],
       [-3.82816813e-02],
       [ 1.86633641e-03],
       [ 6.42463694e-01],
       [ 4.89170873e-01],
       [-9.57545721e-01],
       [-6.55136381e-01],
       [-1.94175489e+00],
       [ 2.13605243e+00],
       [-1.30989594e+00],
       [ 2.14321191e+00]])

In [55]:
a4.reshape(2,8)

array([[-1.14243864e+00,  1.29765299e+00,  2.27934243e-01,
         8.76929194e-01,  1.06671083e-01,  5.47387262e-01,
        -3.82816813e-02,  1.86633641e-03],
       [ 6.42463694e-01,  4.89170873e-01, -9.57545721e-01,
        -6.55136381e-01, -1.94175489e+00,  2.13605243e+00,
        -1.30989594e+00,  2.14321191e+00]])

In [56]:
a4.reshape(2,-1) #but while giving the negative number as reshaping it will automatically create a array based on the given first number(2)

array([[-1.14243864e+00,  1.29765299e+00,  2.27934243e-01,
         8.76929194e-01,  1.06671083e-01,  5.47387262e-01,
        -3.82816813e-02,  1.86633641e-03],
       [ 6.42463694e-01,  4.89170873e-01, -9.57545721e-01,
        -6.55136381e-01, -1.94175489e+00,  2.13605243e+00,
        -1.30989594e+00,  2.14321191e+00]])

In [58]:
#reshape to 3 dimension array
a4.reshape(2,2,4) #we will get (2*4 array as 2 matrix)

array([[[-1.14243864e+00,  1.29765299e+00,  2.27934243e-01,
          8.76929194e-01],
        [ 1.06671083e-01,  5.47387262e-01, -3.82816813e-02,
          1.86633641e-03]],

       [[ 6.42463694e-01,  4.89170873e-01, -9.57545721e-01,
         -6.55136381e-01],
        [-1.94175489e+00,  2.13605243e+00, -1.30989594e+00,
          2.14321191e+00]]])

In [59]:
a1

array(['4', '5', '6', '7', 'Subash', '23.1'], dtype='<U32')

In [60]:
a1[1]

'5'

In [61]:
a1[0]

'4'

In [62]:
a1[4]

'Subash'

In [64]:
a1[2:5]

array(['6', '7', 'Subash'], dtype='<U32')

In [65]:
a1[1:6:2]

array(['5', '7', '23.1'], dtype='<U32')

In [66]:
a1[::-1]

array(['23.1', 'Subash', '7', '6', '5', '4'], dtype='<U32')

In [67]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [68]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
a2[0]

2

In [79]:
a2[:,1:] #ignoring the 0 the index column

array([[2, 3],
       [5, 6]])

In [80]:
a2[:,[1,2]]

array([[2, 3],
       [5, 6]])

In [81]:
a2[:,[0,1]]

array([[1, 2],
       [4, 5]])

In [87]:
a2[[0,1],1:] #[0,1] is get the 0th and 1st row and get the column values from 1st column

array([[2, 3],
       [5, 6]])

In [98]:
a5 = np.random.randint(2,90,(6,5))

In [99]:
a5

array([[18, 48, 50, 80, 84],
       [31, 45, 45, 66,  3],
       [65, 48, 37, 53, 63],
       [78, 82, 21, 51, 46],
       [22,  5, 41, 68, 47],
       [53,  2, 21, 80, 55]])

In [100]:
#get the data where we have values greaterthan 40
a5[a5>40]

array([48, 50, 80, 84, 45, 45, 66, 65, 48, 53, 63, 78, 82, 51, 46, 41, 68,
       47, 53, 80, 55])

In [101]:
a5

array([[18, 48, 50, 80, 84],
       [31, 45, 45, 66,  3],
       [65, 48, 37, 53, 63],
       [78, 82, 21, 51, 46],
       [22,  5, 41, 68, 47],
       [53,  2, 21, 80, 55]])

In [102]:
a5[0,1]

48

In [103]:
#change the valyes of 48(in 1st column 1st row)
a5[0,1]=20

In [104]:
a5

array([[18, 20, 50, 80, 84],
       [31, 45, 45, 66,  3],
       [65, 48, 37, 53, 63],
       [78, 82, 21, 51, 46],
       [22,  5, 41, 68, 47],
       [53,  2, 21, 80, 55]])

In [111]:
a6 = np.random.randint(0,3,(3,3))

In [112]:
a7= np.random.randint(0,3,(3,3))

In [113]:
a6

array([[1, 1, 0],
       [1, 2, 0],
       [1, 0, 1]])

In [114]:
a7

array([[2, 2, 0],
       [2, 0, 0],
       [0, 0, 2]])

In [116]:
a6*a7 #multiplication between two matrixes(this will done by elements multiplication)

array([[2, 2, 0],
       [2, 0, 0],
       [0, 0, 2]])

In [118]:
a6@a7 # mulrtiplication between two matrixes(this will done by matrix multiplication which is actual multiplication)

array([[4, 2, 0],
       [6, 2, 0],
       [2, 2, 2]])

In [119]:
#element addition
a6+100

array([[101, 101, 100],
       [101, 102, 100],
       [101, 100, 101]])

In [120]:
#element multiplication with particular number
a6*0

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [121]:
a6*10

array([[10, 10,  0],
       [10, 20,  0],
       [10,  0, 10]])

In [123]:
a6/0

C:\Users\subas\AppData\Local\Temp\ipykernel_13180\1058679823.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a6/0
C:\Users\subas\AppData\Local\Temp\ipykernel_13180\1058679823.py:1: RuntimeWarning: invalid value encountered in true_divide
  a6/0


array([[inf, inf, nan],
       [inf, inf, nan],
       [inf, nan, inf]])

In [124]:
#power of array elements
a6**2

array([[1, 1, 0],
       [1, 4, 0],
       [1, 0, 1]], dtype=int32)

In [131]:
a8=np.zeros((4,4)) #this will give 4*4 array with zero values

In [132]:
a8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [133]:
a9 = np.ones((4,5)) #this will give 4*5 array with values 1

In [134]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [135]:
a9+10

array([[11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.]])

In [138]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [137]:
#row wise elements addition
a9+np.array([1,2,3,4,5]) # all the a9 elements are adding [1,2,3,4,5] with row wise

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [149]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [150]:
#column wise elements addition
col = np.array([[1,2,3,4]]).T+a9

In [151]:
col

array([[2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [152]:
a6

array([[1, 1, 0],
       [1, 2, 0],
       [1, 0, 1]])

In [153]:
# Rotation of the array(transpose the array)
a6.T

array([[1, 1, 1],
       [1, 2, 0],
       [0, 0, 1]])

In [154]:
a5

array([[18, 20, 50, 80, 84],
       [31, 45, 45, 66,  3],
       [65, 48, 37, 53, 63],
       [78, 82, 21, 51, 46],
       [22,  5, 41, 68, 47],
       [53,  2, 21, 80, 55]])

In [157]:
#square root of every element in the a5
np.sqrt(a5)

array([[4.24264069, 4.47213595, 7.07106781, 8.94427191, 9.16515139],
       [5.56776436, 6.70820393, 6.70820393, 8.1240384 , 1.73205081],
       [8.06225775, 6.92820323, 6.08276253, 7.28010989, 7.93725393],
       [8.83176087, 9.05538514, 4.58257569, 7.14142843, 6.78232998],
       [4.69041576, 2.23606798, 6.40312424, 8.24621125, 6.8556546 ],
       [7.28010989, 1.41421356, 4.58257569, 8.94427191, 7.41619849]])

In [158]:
np.exp(a5)

array([[6.56599691e+07, 4.85165195e+08, 5.18470553e+21, 5.54062238e+34,
        3.02507732e+36],
       [2.90488497e+13, 3.49342711e+19, 3.49342711e+19, 4.60718663e+28,
        2.00855369e+01],
       [1.69488924e+28, 7.01673591e+20, 1.17191424e+16, 1.04137594e+23,
        2.29378316e+27],
       [7.49841700e+33, 4.09399696e+35, 1.31881573e+09, 1.40934908e+22,
        9.49611942e+19],
       [3.58491285e+09, 1.48413159e+02, 6.39843494e+17, 3.40427605e+29,
        2.58131289e+20],
       [1.04137594e+23, 7.38905610e+00, 1.31881573e+09, 5.54062238e+34,
        7.69478527e+23]])

In [159]:
np.log10(a5)

array([[1.25527251, 1.30103   , 1.69897   , 1.90308999, 1.92427929],
       [1.49136169, 1.65321251, 1.65321251, 1.81954394, 0.47712125],
       [1.81291336, 1.68124124, 1.56820172, 1.72427587, 1.79934055],
       [1.8920946 , 1.91381385, 1.32221929, 1.70757018, 1.66275783],
       [1.34242268, 0.69897   , 1.61278386, 1.83250891, 1.67209786],
       [1.72427587, 0.30103   , 1.32221929, 1.90308999, 1.74036269]])

In [172]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [174]:
np.arange(10) #array range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [178]:
np.arange(1.8,10.7,2.5) #we can use the floting in arange but we can't use float in range function

array([1.8, 4.3, 6.8, 9.3])

In [182]:
np.linspace(2,3,num=50) #50 is scale values between the given range.it means range b/w 2 and 3 we will get 2.000,2.111,2.023....etc)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [183]:
np.logspace(2,3,num = 4,base=10)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [185]:
#digonal values will be same which is called as i(eye) matrix
np.eye(5) #5*5 array with same values with digonal values

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Data visualization

# Plotly

In [189]:
!pip install cufflinks

     -------------------------------------- 81.7/81.7 kB 760.6 kB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Using legacy 'setup.py install' for cufflinks, since package 'wheel' is not installed.
  Running setup.py install for cufflinks: started
  Running setup.py install for cufflinks: finished with status 'done'



[notice] A new release of pip available: 22.2.1 -> 22.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [190]:
import cufflinks as cf #to plat any kind of the visualization
import numpy as np
import pandas as pd
import seaborn as sns

In [191]:
cf.go_offline()

In [195]:
np.random.randn(100,3)

array([[ 0.43297105,  2.24275228, -0.10589444],
       [-0.70000082, -0.10764768, -2.50986639],
       [-0.75387534,  0.9240121 ,  0.34759466],
       [ 0.21665023,  1.46785618, -0.10479913],
       [-0.1242761 , -0.19383484, -0.87462466],
       [-1.1703561 ,  1.17607356,  0.67757314],
       [-0.4353218 , -1.77539408, -0.34882251],
       [-1.27304246, -0.18833314,  1.13514679],
       [ 1.42495171, -0.75939947, -0.73813703],
       [ 0.57777594, -1.00122214,  1.17583606],
       [-1.34638521, -0.91094146, -0.02031827],
       [-0.23704429, -2.22895188, -0.19279693],
       [-0.22667849, -0.63648357,  0.87960091],
       [ 2.1205467 ,  0.80589965,  3.06491137],
       [-1.75779151, -0.17821977, -0.54105726],
       [ 1.14260286, -0.04751921,  0.41231861],
       [ 0.86650024,  0.39230345, -1.715833  ],
       [-0.17518274, -2.15672525,  1.21631153],
       [-0.49789613, -0.53630136, -0.08316202],
       [-0.32985283,  0.57633092, -0.73894006],
       [ 0.13736542, -1.80293085,  0.877

In [194]:
#changing to dataframe
pd.DataFrame(np.random.randn(100,3))

0         1         2
0  -0.887419  2.960879  1.236580
1   0.690731 -0.746402 -0.586122
2   0.799989 -0.385835  2.664054
3   1.299314 -0.411939 -0.326623
4  -0.604521  1.353732 -1.347832
..       ...       ...       ...
95  0.790814 -0.170037 -0.415115
96  1.390140  1.021539  1.020246
97 -0.688378  0.939085 -2.102804
98  0.147091  1.486261 -0.124937
99 -0.360134  0.210760 -0.635519

[100 rows x 3 columns]

In [200]:
#change the column names
df = pd.DataFrame(np.random.randn(100,3),columns=['A','B','C'])

In [201]:
df

A         B         C
0   0.245889 -1.863277 -0.547834
1   0.346047  1.183021 -0.311485
2   0.292086 -2.085957 -1.077667
3  -0.395209  0.105719  0.906632
4  -1.424428  0.607077 -0.500137
..       ...       ...       ...
95  1.828883  0.959323 -0.825703
96  0.349450  1.255381 -0.828010
97 -0.190036  1.033264 -0.819344
98  0.488920 -0.524328  0.117391
99  0.993801 -0.147795 -0.710413

[100 rows x 3 columns]

In [202]:
df.iplot()

In [211]:
df.iplot(kind = 'bar')

In [204]:
df1 = pd.DataFrame(np.random.randint(3,100,(100,1)))

In [205]:
df1

0
0   51
1   19
2   26
3   56
4   53
..  ..
95  98
96  64
97  31
98  55
99  71

[100 rows x 1 columns]

In [209]:
df1.iplot()

In [210]:
df1.iplot(kind = 'bar')

In [220]:
#do a comparison between two columns
df.iplot(x='A',y='B',kind = 'bar')

In [221]:
df.iplot(x='A',y='B',mode = 'markers')

In [227]:
#do some action with some dataset which is available already inside the sea born package
df2 = sns.load_dataset('titanic')

In [229]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [232]:
df2.iplot(x='survived',y='sex',kind = 'bar')

In [235]:
df2.iplot(x='age',y='fare',kind = 'bar')

In [238]:
df2.iplot(x='age',y='pclass',kind = 'bar')

In [241]:
df2.iplot(x='fare',y='pclass',mode='markers')